version: '3.4'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    depends_on:
      - database
    ports:
      - ${PORT:-8080}:8080

  database:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
